setup*: shift common vars to common.sh
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/setup-admin b/setup-admin
--- a/setup-admin
+++ b/setup-admin
@@ -2,18 +2,16 @@
 
 set -euo pipefail
 
-scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
-
-XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
-# shellcheck disable=SC2086
-export HOMEBREW_PREFIX=${ADMIN_HOMEBREW_PREFIX:-${HOMEBREW_PREFIX:-$HOME/.brew}}
-PATH="$HOMEBREW_PREFIX/bin:$XDG_DATA_HOME/../bin:$scriptdir/scripts:$PATH"
+HOMEBREW_PREFIX=${ADMIN_HOMEBREW_PREFIX:-${HOMEBREW_PREFIX:-$HOME/.brew}}
 
 # shellcheck source=./components/common.sh
-. "$(dirname "$0")/components/common.sh" || exit 1
+. "$scriptdir/components/common.sh" || exit 1
+
+scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
+PATH="$scriptdir/scripts:$PATH"
 
 if [ "$(id -u)" = "0" ]; then
-    die "Error: Do not run as root"
+    die "Error: Do not run as root, this script expects to use sudo if needed"
 else
     need_sudo
 fi
