Change user shell to zsh if available on Linux
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/components/linux/setup b/components/linux/setup
--- a/components/linux/setup
+++ b/components/linux/setup
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-install_nix
-
 # User shell should be zsh
 if [ -e /bin/zsh ] && [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != /bin/zsh ]; then
     msg "Changing user shell to zsh"
-    sudorun chsh -s /bin/zsh "$LOGNAME"
+    # Failure is ignored here, as in some cases the user password might not be
+    # known or set, as is the case with some container usage.
+    chsh -s /bin/zsh || :
 fi
