Install nix in single user mode on arch under WSL
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/components/arch/setup-admin b/components/arch/setup-admin
--- a/components/arch/setup-admin
+++ b/components/arch/setup-admin
@@ -5,17 +5,22 @@ pacman() {
 }
 
 install_nix() {
-    pacman -S nix
+    if [ "$OSTYPE" = WSL ]; then
+        sh <(curl -L https://nixos.org/nix/install) --no-daemon
+    else
+        pacman -S nix
 
-    sudorun systemctl enable nix-daemon
-    sudorun systemctl start nix-daemon
-    if ! grep -q "^nix-users:.*$USER" /etc/group; then
-        sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
         if ! grep -q "^nix-users:.*$USER" /etc/group; then
-            echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
-        else
-            echo >&2 "User has been added to the nix-users group, please re-login"
+            sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
+            if ! grep -q "^nix-users:.*$USER" /etc/group; then
+                echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
+            else
+                echo >&2 "User has been added to the nix-users group, please re-login"
+            fi
         fi
+
+        sudorun systemctl enable nix-daemon
+        sudorun systemctl start nix-daemon
     fi
 }
 
